S06US33_cost
WildCodeSchool/orleans-php-2003-project-cotoit pull request #124
Opened 2020-07-06 13:04 UTC by eozen-git

2020-07-06 13:05 UTC, Heldeenn submitted a review, later dismissed

2020-07-06 13:32 UTC, sblondeau requested changes
dans l'ensemble c'est plutot bien
je pense que tu boucles trop souvent sur housing, c'est sans doute optimisable, mais pour l'instant ça fera très bien l'affaire ;-)
pense à bien nommer et bien documenter tes classes

2020-07-06 13:32 UTC, sblondeau commented on src/Repository/HourlyRateRepository.php
> +    //  * @return HourlyRate[] Returns an array of HourlyRate objects
code commenté à virer

2020-07-06 13:32 UTC, sblondeau commented on src/Service/CalculatingManager.php
> +    public function profitLot(array $housings): float
quand tu travailles sur de méthodes de service, hésite pas à mettre des code PHPDocs (PHPStorm te les génère) et en 1ere ligne du PHPDocs tu mets une petite phrase courte et simple en anglais pour dire à quoi sert la méthode

2020-07-06 13:32 UTC, sblondeau commented on src/Service/CalculatingManager.php
> +        return round($totalTime, 2);
je suis pas sur que tu doives faire l'arrondi ici, alors que tu refais un arrondi plus tard sur ProfitLot, c'est un risque d'avoir un total trop approximé. Je pense qu'il vaut mieux ne garder que le round() final

2020-07-06 13:32 UTC, sblondeau commented on src/Service/CalculatingManager.php
> +    private function globalCost(array $housings)
pense au typage de retour sur toutes tes méthodes

2020-07-06 13:32 UTC, sblondeau commented on src/Service/CalculatingManager.php
> +    private function profit(float $revenue, float $cost)
je me demande si tu ne fais pas  trop de découpage là... cette méthode va tu la réutiliser ailleurs ? si oui impec, si non, je suis pas sur que ça vaille le coup de la séparer de profitLot pour juste une ligne

2020-07-06 13:32 UTC, sblondeau commented on src/Service/CalculatingManager.php
> +        return round($profit / $totalLots, 2);
ça ne va pas là, tu dois t'assurer sur $totalLots est différent de zéro sinon ta division risque de te renvoyer une erreur.

2020-07-06 14:23 UTC, eozen-git commented on src/Service/CalculatingManager.php
> +    private function profit(float $revenue, float $cost)
On va la réutiliser sur d'autres calculs oui.

2020-07-06 15:29 UTC, Heldeenn approved these changes

2020-07-07 08:02 UTC, sblondeau approved these changes

2020-07-07 08:02 UTC, merged