US03SP02navbar
WildCodeSchool/orleans-php-2003-project-cotoit pull request #14
Opened 2020-06-04 12:49 UTC by maoherve

2020-06-04 12:57 UTC, eozen-git requested changes

2020-06-04 12:57 UTC, eozen-git commented on templates/include/navbar.html.twig
> +                <a class="NBlink nav-link" href="#">Accueil</a>
Tu peux mettre le lien de la page actuelle pour "accueil" je pense, vu que ça sera la page principale.
Pas sûr qu'il faille laisser les boutons si les liens sont non fonctionnels d'ailleurs.

2020-06-04 13:17 UTC, eozen-git submitted a review, later dismissed

2020-06-04 14:57 UTC, sblondeau requested changes

2020-06-04 14:57 UTC, sblondeau commented on assets/scss/navbar.scss
> +.NB {
pas de majuscule dans les noms de classe stp. Et si plusieurs mots, plutot des tiret "my-class"

2020-06-04 14:57 UTC, sblondeau commented on assets/scss/navbar.scss
> +.NBlink {
idem

2020-06-04 14:57 UTC, sblondeau commented on assets/scss/navbar.scss
> +.NB {
et des nommage explicite. Je sais pas ce que c'est NB ? number ? navbar ?

2020-06-04 14:57 UTC, sblondeau commented on webpack.config.js
> +        //to: 'images/[path][name].[ext]',
tu peux aussi decommenter cette ligne pour que ça recréé un dossier images dans build, sinon ça mets tout en vrac dans build je trouve ça moins propre (attention d'avoir tous la meme config niveau de votre webpack.config sinon vous aurez des conflits ;-) )

2020-06-04 16:29 UTC, eozen-git approved these changes

2020-06-05 06:54 UTC, sblondeau approved these changes

2020-06-05 06:54 UTC, merged