header
WildCodeSchool/orleans-php-2003-project-cotoit pull request #15
Opened 2020-06-04 15:17 UTC by MonyaMya

2020-06-04 15:28 UTC, eozen-git requested changes

2020-06-04 15:28 UTC, eozen-git commented on assets/scss/header.scss
> +    padding-block: spacing;
Oublies pas le '$' quand tu fais appel à une variable. Ici c'est $spacing

2020-06-04 15:43 UTC, eozen-git submitted a review, later dismissed

2020-06-04 16:08 UTC, sblondeau requested changes

2020-06-04 16:08 UTC, sblondeau commented on templates/home/header.html.twig
> +        <h3 class="text-center">Cet outil vous permet d’analyser la performance de vos portefeuilles de gestion de copropriété </h3>
si c'est après h1, il faut mettre h2 et non h3
et tu gères le style via CSS

2020-06-05 07:46 UTC, Heldeenn approved these changes

2020-06-05 08:20 UTC, sblondeau approved these changes

2020-06-05 08:20 UTC, merged