création User Fixture
WildCodeSchool/orleans-php-2003-project-cotoit pull request #33
Opened 2020-06-10 08:00 UTC by maoherve

Création d'un utilisateur avec fixture

2020-06-10 08:22 UTC, Heldeenn submitted a review, later dismissed

2020-06-10 08:48 UTC, sblondeau requested changes
c'est pas mal dans l'ensemble, par contre on s'est pas bien compris
tu dois gérer le login d'un User, ça c'est ta US
et les fixtures sur User sont donc juste une tache supplémentaire à ta US
donc là il me faut aussi le code du formulaire de login et le traitement de la connexion. 
mais pas de code sur le Registration ;-)

2020-06-10 08:48 UTC, sblondeau commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=180, unique=true)
manque les Assert

2020-06-10 08:48 UTC, sblondeau commented on src/Migrations/Version20200610073246.php
> +<?php
pas de migration sur les projets3, mais doctrine:schema:update
donc retire le fichier

2020-06-10 08:48 UTC, sblondeau commented on src/Repository/UserRepository.php
> +    //  * @return User[] Returns an array of User objects
enlève le code commenté (meme si généré par Sf)

2020-06-10 09:12 UTC, maoherve commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=180, unique=true)
ok my bad

2020-06-10 14:52 UTC, eozen-git requested changes
Edit : Commentaire supprimé, pas pertinent

2020-06-10 14:52 UTC, eozen-git commented on assets/scss/login.scss
> +    background-color: $background-color !important;
C'est déconseillé d'utiliser "!important" apparemment. Si tu cibles directement le .btn-primary de bootstrap, il devrait te changer le background sans soucis.

2020-06-11 07:53 UTC, eozen-git approved these changes
Bien joué!

2020-06-11 08:13 UTC, sblondeau approved these changes

2020-06-11 08:13 UTC, merged