S02US21 admin grille de temps
WildCodeSchool/orleans-php-2003-project-cotoit pull request #39
Opened 2020-06-11 13:27 UTC by eozen-git

Pas mal de fichiers car obligé de faire la résolution de conflits en local et création de l'entité/crud etc..

2020-06-11 13:38 UTC, maoherve submitted a review, later dismissed

2020-06-11 13:56 UTC, maoherve submitted a review, later dismissed

2020-06-11 15:03 UTC, maoherve submitted a review, later dismissed

2020-06-11 15:35 UTC, Heldeenn submitted a review, later dismissed

2020-06-11 16:11 UTC, Heldeenn submitted a review, later dismissed

2020-06-11 16:21 UTC, sblondeau requested changes

2020-06-11 16:21 UTC, sblondeau commented on src/Controller/.gitignore
> +ActivityController.php
hum ? pourquoi ce fichier est dans le gitignore ?

2020-06-11 16:21 UTC, sblondeau commented on src/Entity/Activity.php
> +     * @Assert\NotBlank(message="Le nombre de minutes allouées à l'activité doit être défini")
est-ce vraiment nécessaire ? 
on peut pas partir du principe que si l'user laisse le champ vide, ça signifie "0"
garde ça pour un fix plus tard éventuelellement, mais niveau UX ça me parait mieux... ou alors il faut que zéro apparaissent par défaut dans le champ ce qui est peut etre le cas, j'ai pas encore tout lu :D

2020-06-11 16:27 UTC, eozen-git commented on src/Controller/.gitignore
> +ActivityController.php
Je ne fais que l'admin d'Activity sur cet US - Je l'ai mis dans le gitignore tant que la partie utilisateur est pas faite

2020-06-11 16:39 UTC, Heldeenn submitted a review, later dismissed

2020-06-12 07:18 UTC, sblondeau requested changes

2020-06-12 07:18 UTC, sblondeau commented on src/Controller/.gitignore
> +ActivityController.php
non tu ne t'y prends pas bien niveau Git
tu ne dois pas le mettre dans le gitignore car le fichier gitignore EST versionné et ce fichier sera donc non versionné chez tout le monde (il se pourrait que d'autres aient besoin de bosser dessus aussi).
Il faut juste que tu n'add pas ce fichier quand tu fais ton git add.
ou que tu fasse un git rm s'il est déjà versionné
Bref je ne le veux pas dans le gitignore ;-)

2020-06-12 07:29 UTC, Heldeenn approved these changes

2020-06-12 08:22 UTC, sblondeau approved these changes

2020-06-12 08:23 UTC, merged