Sp03 us25 create link to navigate in admin home
WildCodeSchool/orleans-php-2003-project-cotoit pull request #65
Opened 2020-06-17 14:38 UTC by maoherve

lien dans admin plus modification nav bar admin

2020-06-17 15:03 UTC, eozen-git submitted a review, later dismissed

2020-06-17 18:41 UTC, sblondeau requested changes

2020-06-17 18:41 UTC, sblondeau commented on templates/admin/_adminSection.html.twig
> +                    <a href="{{ path('admin_activity_index') }}" class="card-text">Modifier les activitées</a>
activités

2020-06-18 17:03 UTC, eozen-git approved these changes

2020-06-18 19:42 UTC, sblondeau approved these changes

2020-06-18 19:42 UTC, merged