Us08 09 admin manuals index
WildCodeSchool/orleans-php-2003-project-cotoit pull request #66
Opened 2020-06-17 17:35 UTC by MonyaMya

2020-06-18 07:33 UTC, maoherve submitted a review, later dismissed

2020-06-18 11:58 UTC, sblondeau requested changes

2020-06-18 11:58 UTC, sblondeau commented on src/Controller/ManualController.php
> +            'manuals' => $manualRepository->findAll(),
je serais pas parti sur cette façon de faire au niveau de ta table...
tu as 2 parties, le mode d'emploi et les méthodes de calcul. Il n'y en aura jamais d'autre. 
Donc tu devrais plutot avoir 1 seule table Manual (ça ok) mais avec 2 champ de type TEXT, par ex "instruction" et "calculationMethod". Et dans cette table tu as toujours une seule ligne. 

donc ici tu récupère $manual = $manualRepository->findOneBy([]) 
et dans ton twig, pas de boucle mais direct un manual.instruction et un manual.calculationMethod qui va te récupérer les infos. Le "titre" de la partie n'a pas besoin d'être administrable je pense.

2020-06-18 11:58 UTC, sblondeau commented on src/Controller/ManualController.php
> +    public function new(Request $request): Response
du coup tu n'as pas besoin de la partie new ou delete du crud, juste de l'index et de l'edit

2020-06-18 11:58 UTC, sblondeau commented on src/Form/ManualType.php
> +            ->add('text', TextareaType::class)
dans le form, tu as juste 
->add('instruction') et ->add('calculationMethod')

2020-06-22 07:06 UTC, eozen-git requested changes

2020-06-22 07:06 UTC, eozen-git commented on src/DataFixtures/ManualFixtures.php
> +            $manual->setInstruction($title);
Le setInstruction doit être aussi être du texte, ça correspond au texte du mode d'emploi dans la carte.

2020-06-22 07:06 UTC, eozen-git commented on src/Migrations/Version20200621114622.php
> +}
Sylvain ne veut pas de fichier de migration. Supprimes ce fichier et utilises plutôt doctrine:schema:update --force pour mettre à jour ta bdd.

2020-06-22 08:30 UTC, eozen-git submitted a review, later dismissed

2020-06-22 11:27 UTC, sblondeau submitted a review, later dismissed

2020-06-22 14:21 UTC, merged