S05US30 récupération données
WildCodeSchool/orleans-php-2003-project-cotoit pull request #91
Opened 2020-06-30 13:41 UTC by Heldeenn

2020-06-30 13:43 UTC, eozen-git submitted a review, later dismissed

2020-06-30 16:03 UTC, sblondeau requested changes

2020-06-30 16:03 UTC, sblondeau commented on src/Entity/Housing.php
> +<?php
cette classe est inutile dans cette PR vu que tu ne l'utilises pas.
de plus il manquerait les Assert

2020-06-30 16:03 UTC, sblondeau commented on src/Entity/Housing.php
> +<?php
ah en non en fait ça ne va pas. Là vous devez creer une classe qui va contenir vos données, mais ce n'est pas relier à la BDD. Donc pas d'annotations @ORM ici (il ne faut pas passer par le maker en fait là)
le plus siple est d'enlever cette classe de la PR pour le moment

2020-07-01 13:17 UTC, maoherve approved these changes

2020-07-01 15:07 UTC, sblondeau approved these changes

2020-07-01 15:07 UTC, merged