S05US13 création hydratation entity housing
WildCodeSchool/orleans-php-2003-project-cotoit pull request #96
Opened 2020-07-01 15:18 UTC by Heldeenn

On a pas fait la vérification des erreurs dans cette PR, on la fera dans une autre.

2020-07-01 15:22 UTC, eozen-git submitted a review, later dismissed

2020-07-01 19:40 UTC, sblondeau requested changes

2020-07-01 19:40 UTC, sblondeau commented on src/Service/PopulatingManager.php
> +    private function removeSpecialCharacters(string $input)
cette méthode est-elle vraiment nécessaire? avez vous tester si garder les caractères spéciaux fait planter le script?  
si nécessaire, plutot que de faire ça, ne vaudrait-il pas mieux convertir les noms en "slug" ?
par ailleurs, il y a une toute récente class String dans symfony pour tout ce qui est manipulation et transformation de string (notamment du slug) 
c'est intégré depuis la version 5.1 mais je pense que ça fonctionne sur une 4.4 (à tester éventuellement). https://symfony.com/doc/current/components/string.html

2020-07-01 19:40 UTC, sblondeau commented on src/Controller/HomeController.php
> +            $session->set('userHousing', $populatingManager->populateHousing($session->get('portfolio')));
j'ai cru qu'on ne faisait tout le "populating" que sur la page du formulaire ? et que là on se contentait juste d'envoyer le fichier décodé "brut" en session ?

2020-07-01 19:40 UTC, sblondeau commented on src/Service/PopulatingManager.php
> +        $activities = array_slice($property, 7, null, true);
2 choses
- cette méthode a la responsabilité de transfo en int, ok. C'est pas son role de faire le array_slice par contre. Ca devrait etre fait dans populateHousing ou eventuellement dans une autre méthode. 
Gardez le principe une méthode = une chose
- ensuite pour ce array_slice, le "7" j'imagine que c'est pour la colonne 7 ? ça devrait etre dans une constante. Ou mieux, vous devriez avoir une constante contenant un tableau de toutes les colonne "non variables" et la le 7 serait remplacé par count(self::FIXED_COLUMNS)

2020-07-01 19:40 UTC, sblondeau commented on src/Service/PopulatingManager.php
> +            $activities['nombre de visites'] = intval($property['nombre de visites']);
et utiliser cette constante FIXED_COLUMNS pour toutes les "clés" de tableau codées ici en dur. Ca sera beaucoup plus propre. En tout cas c'est l'idée, on peut en rediscuter et adapter si besoin ;-)

2020-07-01 19:40 UTC, sblondeau commented on src/Service/PopulatingManager.php
> +            $property['hono'] = ltrim(str_replace(' ', '', $property['hono']));
ah... je pensais que le intval() suffirait aussi pour cette colonne. Vous avez tester ? ça marche pas ?

2020-07-01 23:56 UTC, eozen-git commented on src/Service/PopulatingManager.php
> +    private function removeSpecialCharacters(string $input)
Concernant le composant String, le composer require me dit que le package n'est pas dispo pour la 4.4 malheureusement.

Pour l'utilité de la méthode, étant donné qu'ensuite on se sert du nom de chaque colonne du fichier csv en dur comme clé pour hydrater l'objet housing, c'est important qu'on élimine au maximum toutes les petites variations qu'on pourrait avoir au niveau du nom des colonnes du fichier.
Vu qu'on a aucune idée des manips effectuées au niveau de chaque agence au moment de l'export des données vers leur csv (notamment est-ce qu'ils nomment les colonnes ? Ce qui serait pas impossible vu les abbréviations utilisées dans le fichier type), ça nous a semblé important d'éliminer le risque. Après, à charge dans le mode d'emploi d'indiquer quelles colonnes on attend et que le nom de chaque colonne doit être tel ou tel. Et idéalement de fournir un fichier éxemple.

Pour le slug ça serait judicieux oui. Dans l'état actuel du code, il suffit juste qu'on change les espaces par des tirets et on l'obtient. Limite on pourrait déporter les deux méthodes dans son propre service Slugify ce qui le rendrait utilisable pour d'autres cas.

2020-07-02 00:29 UTC, eozen-git commented on src/Service/PopulatingManager.php
> +            $property['hono'] = ltrim(str_replace(' ', '', $property['hono']));
On a utilisé floatval vu que les honoraires sont en décimal. Mais par éxemple, 4 681,50 nous renvoyait 4.6. Il interprètait l'espace comme un '.' et vu que c'est un espace comptable (unicode différent d'un simple espace), on a été obligé de copier/coller l'espace venant directement du formatage du fichier dans le paramètre de str_replace pour qu'il le reconnaisse.
On a essayé avec preg_replace, ce qu'aurait été plus élégant et moins risqué en cas de modification du service mais il nous renvoit une erreur quand on utilise l'unicode ( \u202F ou \x{202F} ).

2020-07-02 08:01 UTC, eozen-git submitted a review, later dismissed

2020-07-02 08:03 UTC, eozen-git commented on src/Controller/HomeController.php
> +            $session->set('userHousing', $populatingManager->populateHousing($session->get('portfolio')));
C'est un moyen pour nous de mieux répartir le travail entre les US.

2020-07-02 08:09 UTC, sblondeau requested changes

2020-07-02 08:09 UTC, sblondeau commented on src/Service/PopulatingManager.php
> +        'nom-de-la-copropriete',
je voyais plus un truc comme
 
    const FIXED_COLUMNS = [
       'HOUSING_NAME' =>'nom-de-la-copropriete', 
       'POSTAL_CODE' => 'cp', 
... ];

donc ensuite dans ton code tu utiliserais self::FIXED_COLUMNS['POSTAL_CODE'] et non self::FIXED_COLUMNS[1]
ce n'est qu'une question de lisibilité du code.

2020-07-02 08:10 UTC, sblondeau commented on src/Service/PopulatingManager.php
> +    private function removeSpecialCharacters(string $input)
impeccable :+1:

2020-07-02 08:15 UTC, sblondeau requested changes

2020-07-02 08:15 UTC, sblondeau commented on src/Service/ParsingManager.php
> +    public function convertToBoolean(string $input)
vous ne convertissez pas en boolean là, car un bool c'est true ou false et non 0 ou 1 (meme si PHP le traite pareil). Donc changez peut etre le nom de la méthode et type la sortie en :int

2020-07-02 08:15 UTC, sblondeau commented on src/Service/PopulatingManager.php
> +            $property[self::FIXED_COLUMNS[3]] = ltrim(str_replace(' ', '', $property[self::FIXED_COLUMNS[3]]));
ça serait plus pertinent de faire une méthode par ex moneyToFloat (pourquoi pas dans votre ParsingService qui va etre un service qui va faire tous les petits ajustements sur vos valeurs récupécrée)
et vous auriez un truc comme $this->parsing->moneyToFloat($property[self::FIXED_COLUMNS['HONORARY'])

2020-07-02 09:00 UTC, eozen-git approved these changes

2020-07-02 09:14 UTC, sblondeau approved these changes

2020-07-02 09:14 UTC, merged